---
version: "3.3"

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  seeddb:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    entrypoint: >
                /bin/sh -c 'sleep 5 && migrate -path=/migrations/ -database
                "mongodb://root:example@mongo:27017/main?authSource=admin" up'
    depends_on:
      - "mongo"

  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      GIN_MODE: release
    links:
      - redis
      - mongo
    depends_on:
      - mongo
      - redis

  frontend:
    build: frontend
    ports:
      - 4200:4200
    restart: "always"
    volumes:
      - ./frontend:/app
